; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32532.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	main
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File C:\Users\roryh\source\repos\c_compiler\c_compiler\test.c
; Line 2
	mov	eax, 2
; Line 3
	ret	0
main	ENDP
_TEXT	ENDS
END
